#!/usr/bin/env python3
"""Regenerate docs/samples/ from the fictional example matter.

    python3 scripts/make_samples.py

Runs the same commands a person runs and keeps what they print. The brief uses a fixed date
(Mon Oct 5 2026) so the samples read the same on every run.
"""
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
M = os.path.join(ROOT, "examples", "doe-v-roe")
OUT = os.path.join(ROOT, "docs", "samples")
CLI = [sys.executable, os.path.join(ROOT, "bin", "cursitor")]
TODAY = "2026-10-05"


ENV = dict(os.environ, RL_invariant="1")     # fixed PDF timestamps


def run(*args, ok=(0,)):
    r = subprocess.run(CLI + list(args), stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=ROOT, env=ENV)
    if r.returncode not in ok:
        sys.stderr.write(r.stderr.decode())
        raise SystemExit("failed: cursitor %s (exit %d)" % (" ".join(args), r.returncode))
    return r.stdout.decode("utf-8")


def write(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as fh:
        fh.write(text if text.endswith("\n") else text + "\n")
    print("  " + name)


def rel(p):
    return os.path.relpath(p, ROOT)


def main():
    os.makedirs(OUT, exist_ok=True)
    print("docs/samples:")
    clean = os.path.join(OUT, "complaint-clean.txt")
    run("paste-clean", rel(os.path.join(M, "paste", "complaint-pasted.txt")), "-o", rel(clean))
    print("  complaint-clean.txt")
    run("plead", rel(clean), rel(os.path.join(OUT, "complaint.pdf")), "--caption",
        rel(os.path.join(M, "caption-complaint.json")), "--matter", rel(M))
    print("  complaint.pdf")

    tmp = tempfile.mkdtemp(prefix="cursitor-samples-")
    try:
        run("exhibits", rel(os.path.join(M, "exhibits")), tmp, "--prefix", "DOE")
        shutil.copyfile(os.path.join(tmp, "exhibits-package.pdf"), os.path.join(OUT, "exhibits-package.pdf"))
        shutil.copyfile(os.path.join(tmp, "index.txt"), os.path.join(OUT, "exhibits-index.txt"))
        print("  exhibits-package.pdf\n  exhibits-index.txt")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    run("deadline", "ics", rel(os.path.join(M, "calendar.json")), rel(os.path.join(OUT, "calendar.ics")))
    print("  calendar.ics")
    write("brief.txt", run("brief", rel(M), "--today", TODAY, "--no-docket"))
    draft = os.path.join(M, "drafts", "2026-10-02 meet-and-confer letter.txt")
    gate_out = run("gate", rel(draft), rel(M), ok=(1,))
    write("gate-blocked.txt", gate_out.replace(ROOT + os.sep, ""))

    ex = [
        ("1. California discovery responses, served by email over Labor Day",
         ["deadline", "from", "--served", "2026-08-05", "--method", "email", "--rule", "ca.discovery_response"]),
        ("2. California requests for admission, served by mail inside California (the example matter's next deadline)",
         ["deadline", "from", "--served", "2026-09-04", "--method", "mail", "--rule", "ca.rfa_response"]),
        ("3. California motion to compel further responses: 45 days from verified responses served by email",
         ["deadline", "from", "--served", "2026-09-09", "--method", "email", "--rule", "ca.motion_compel_further"]),
        ("4. California §12a roll: served by hand, the 30th day falls on a Saturday before Labor Day",
         ["deadline", "from", "--served", "2026-08-06", "--method", "personal", "--rule", "ca.rog_response"]),
        ("5. Federal requests for production: Rule 6(d) adds 3 days for mail, none for electronic service",
         ["deadline", "from", "--served", "2026-08-05", "--method", "mail", "--rule", "fed.rfp_response"]),
    ]
    lines = ["DEADLINE EXAMPLES", "",
             "Each date is printed with the arithmetic that produced it. Generated by `cursitor deadline from`; the command is on the line under each heading.", ""]
    for head, args in ex:
        lines.append(head)
        lines.append("$ cursitor " + " ".join(args))
        lines.append(run(*args).rstrip())
        if args[-1] == "fed.rfp_response":
            alt = args[:]
            alt[alt.index("mail")] = "email"
            lines.append("$ cursitor " + " ".join(alt))
            lines.append(run(*alt).rstrip())
        lines.append("")
    write("deadline-examples.txt", "\n".join(lines))

    sched = run("deadline", "brief-schedule", "--hearing", "2026-12-03", "--time", "9:00 a.m.", "--rules", "ca")
    sched += "\n" + run("deadline", "brief-schedule", "--hearing", "2026-10-05", "--rules", "ca")
    write("brief-schedule.txt", sched)
    for f in sorted(os.listdir(OUT)):
        print("  %-24s %8d bytes" % (f, os.path.getsize(os.path.join(OUT, f))))


if __name__ == "__main__":
    main()
